### ISSUE TITLE
cTentacleAgent Get-TentacleThumbprint always return blank thumbprint

### ISSUE THREAD

**Issue by inghak** [OctopusDeploy/OctopusDSC#246] opened 2020-01-24 16:32 UTC
`cTentacleAgent ` `Get-TentacleThumbprint` always return blank/null thumbprint.

This is because the supporting function `Invoke-TentacleCommand` in `OctopusDscHelpers.ps1` does not return a value.

So: 
`$thumbprint = Invoke-TentacleCommand @("show-thumbprint", "--instance", $Instance, "--console", "--thumbprint-only")`

in `Get-TentacleThumbprint`

can never get a value because `Invoke-TentacleCommand` never return one.

If I modify  `Invoke-TentacleCommand` to return the value, it works. I could fix the problem for me by adding one line of code, `return $output` at the end of `Invoke-TentacleCommand` :

```
    Write-Verbose "done."
    return $output
}

```
This creates a problem, at least, in `cTentacleAgent` when comparing the number of environments. I get a lot of false `Not Compliant` due to this.

**Comment by matt-richardson** [comment] 2020-01-24 19:18
Thanks for reporting, @inghak. This is a duplicate of https://github.com/OctopusDeploy/OctopusDSC/issues/242.

Unfortunately, our test pipeline is broken for this project (due to some upstream breaking changes in `Octopus.Client`), which limits our ability to get a new release out. I'll have a chat with the team to see if we can bump the priority of that fix.

**Closed** 2020-04-12 22:01 UTC

**Comment by matt-richardson** [comment] 2020-04-13 00:47
Released in version 4.0.884
